import {Platform, Dimensions, PixelRatio} from 'react-native'
const deviceWidth = width = Dimensions.get('window').width
import {PRIMARY, RED, GREY} from '../../constants'

export default {
  '.p': {padding: 10},
  '.pt': {paddingTop: 10},
  '.pr': {paddingRight: 10},
  '.pb': {paddingBottom: 10},
  '.pl': {paddingLeft: 10},
  '.bp': {padding: 15},
  '.bpt': {paddingTop: 15},
  '.bpr': {paddingRight: 15},
  '.bpb': {paddingBottom: 15},
  '.bpl': {paddingLeft: 15},
  '.sp': {padding: 5},
  '.spt': {paddingTop: 5},
  '.spr': {paddingRight: 5},
  '.spb': {paddingBottom: 5},
  '.spl': {paddingLeft: 5},
  '.m': {margin: 10},
  '.mt': {marginTop: 10},
  '.mr': {marginRight: 10},
  '.mb': {marginBottom: 10},
  '.ml': {marginLeft: 10},
  '.bm': {margin: 15},
  '.bmt': {marginTop: 15},
  '.bmr': {marginRight: 15},
  '.bmb': {marginBottom: 15},
  '.bml': {marginLeft: 15},
  '.sm': {margin: 5},
  '.smt': {marginTop: 5},
  '.smr': {marginRight: 5},
  '.smb': {marginBottom: 5},
  '.sml': {marginLeft: 5},
  '.full': {width: '100%'},
  '.flex1': {display: 'flex', flex: 1},
  '.flex2': {display: 'flex', flex: 2},
  '.flex3': {display: 'flex', flex: 3},
  '.flex4': {display: 'flex', flex: 4},
  '.flex5': {display: 'flex', flex: 5},
  '.flex6': {display: 'flex', flex: 6},
  '.full': {width: '100%'},
  '.fullW': {width},
  '.fullh': {height: '100%'},
  '.half': {width: '50%'},
  '.bordered': {borderWidth: 1, borderColor: GREY},
  '.border': {borderWidth: 1, borderColor: GREY},
  '.bordert': {borderTopWidth: 1, borderColor: GREY},
  '.borderl': {borderLeftWidth: 1, borderColor: GREY},
  '.borderb': {borderBottomWidth: 1, borderColor: GREY},
  '.borderr': {borderRightWidth: 1, borderColor: GREY},
  '.bottom': {position: 'absolute', bottom: 0},
  '.top': {position: 'absolute', top: 0},
  '.top-right': {position: 'absolute', top: 0, right: 0},
  '.big-size': {width: '100%', height: 160},
  '.big-size-square': {width: 160, height: 160},
  '.big-size-rounded': {width: 160, height: 160, borderRadius: 80},
  '.normal-size': {width: '100%', height: 100},
  '.normal-size-square': {width: 100, height: 100},
  '.normal-size-rounded': {width: 100, height: 100, borderRadius: 50},
  '.small-size': {width: '100%', height: 50},
  '.small-size-square': {width: 50, height: 50},
  '.small-size-rounded': {width: 50, height: 50, borderRadius: 25},
  '.tiny-size': {width: '100%', height: 28},
  '.tiny-size-square': {width: 28, height: 28},
  '.tiny-size-rounded': {width: 28, height: 28, borderRadius: 14},
  '.icon-btn-size': {width: '100%', height: 32},
  '.icon-btn-size-square': {width: 32, height: 32},
  '.icon-btn-size-rounded': {width: 32, height: 32, borderRadius: 16},
  '.icon-size': {width: '100%', height: 24},
  '.icon-size-square': {width: 24, height: 24},
  '.icon-size-rounded': {width: 24, height: 24, borderRadius: 12},
}
